services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r!
      MYSQL_DATABASE: weavon
  redis:
    image: redis:latest
    ports:
      - "6379:6379"