spring:
  application:
    name: weavon-server

  datasource:
    url: jdbc:mysql://localhost:3306/weavon?serverTimezone=UTC&encoding=UTF-8
    username: root
    password: 1q2w3e4r!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_SECRET}
            scope:
              - email
              - profile

  messages:
    basename: internationalize/label_en, internationalize/label_kr, internationalize/message_en, internationalize/message_kr
    encoding: UTF-8
    fallback-to-system-locale: false
    always-use-message-format: true

jwt:
  key: WEAVON_JWT_SECRET_KEY
