spring:
  application:
    name: weavon-server

  messages:
    basename: internationalize/label, internationalize/message
    encoding: UTF-8
    fallback-to-system-locale: false
    always-use-message-format: true
