INSERT INTO user (user_id, username, password, nickname, email, role)
VALUES (1,
        'admin',
        '$2a$10$08p7rWHZiGS1TnZveYvd9..zAN0h9YGugNa/JAfvPsUObjFdJrNuu',
        '관리자',
        'admin@email.com',
        'ADMIN'),
       (2,
        'userA',
        '$2a$10$08p7rWHZiGS1TnZveYvd9..zAN0h9YGugNa/JAfvPsUObjFdJrNuu',
        '사용자 A',
        'userA@email.com',
        'USER'),
       (3,
        'userB',
        '$2a$10$08p7rWHZiGS1TnZveYvd9..zAN0h9YGugNa/JAfvPsUObjFdJrNuu',
        '사용자 B',
        'userB@email.com',
        'USER'),
       (4,
        'userC',
        '$2a$10$08p7rWHZiGS1TnZveYvd9..zAN0h9YGugNa/JAfvPsUObjFdJrNuu',
        '사용자 C',
        'userC@email.com',
        'USER'),
       (5,
        'userD',
        '$2a$10$08p7rWHZiGS1TnZveYvd9..zAN0h9YGugNa/JAfvPsUObjFdJrNuu',
        '사용자 D',
        'userD@email.com',
        'USER'),
       (6,
        'userE',
        '$2a$10$08p7rWHZiGS1TnZveYvd9..zAN0h9YGugNa/JAfvPsUObjFdJrNuu',
        '사용자 E',
        'userE@email.com',
        'USER'),
       (7,
        'userF',
        '$2a$10$08p7rWHZiGS1TnZveYvd9..zAN0h9YGugNa/JAfvPsUObjFdJrNuu',
        '사용자 F',
        'userF@email.com',
        'USER');